# ~/.alacritty.toml

import = [
	# "~/.config/global/themes/alacritty/gruvbox_light.toml"
	# "~/.config/global/themes/alacritty/gruvbox_dark.toml"
	"~/.config/global/themes/alacritty/one_dark.toml"
]

[font]
size = 10
normal = { family = "Fira Code", style = "Regular" }

[window]
opacity = 0.92
padding = { x = 12, y = 12 }
